Section B

In [1]:
import numpy as np

# Create a scalar using np.array(5)
scalar = np.array(5)
print("Scalar array:")
print(scalar)
print(f"Shape: {scalar.shape}")
print(f"Type: {type(scalar)}")
print()

# Create a 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print(f"Shape: {array_1d.shape}")
print()

# Create a 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array (2x3):")
print(array_2d)
print(f"Shape: {array_2d.shape}")
print()

# Alternative method using reshape
array_2d_alt = np.arange(10, 70, 10).reshape(2, 3)
print("2D Array using arange and reshape:")
print(array_2d_alt)

Scalar array:
5
Shape: ()
Type: <class 'numpy.ndarray'>

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array (2x3):
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)

2D Array using arange and reshape:
[[10 20 30]
 [40 50 60]]


In [3]:
# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))  # 101 is exclusive

print("4x4 Random Integer Array (0-100):")
print(random_array)
print(f"Shape: {random_array.shape}")
print(f"Data type: {random_array.dtype}")

# Additional operations to demonstrate numpy functionality
print("\nArray Statistics:")
print(f"Minimum value: {random_array.min()}")
print(f"Maximum value: {random_array.max()}")
print(f"Mean: {random_array.mean():.2f}")
print(f"Standard deviation: {random_array.std():.2f}")

4x4 Random Integer Array (0-100):
[[18 57 12 67]
 [95 33 50 35]
 [62 66 37 51]
 [30 86  8 43]]
Shape: (4, 4)
Data type: int32

Array Statistics:
Minimum value: 8
Maximum value: 95
Mean: 46.88
Standard deviation: 24.07


In [4]:
import pandas as pd

# Create a 3x3 numpy array
np_array = np.array([[1, 2, 3],
                     [4, 5, 6], 
                     [7, 8, 9]])

print("Original Numpy Array (3x3):")
print(np_array)
print(f"Shape: {np_array.shape}")
print()

# Convert to pandas DataFrame with column names
df = pd.DataFrame(np_array, columns=['A', 'B', 'C'])

print("Pandas DataFrame:")
print(df)
print(f"DataFrame shape: {df.shape}")
print()

# Display DataFrame info
print("DataFrame Info:")
print(df.info())

Original Numpy Array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
DataFrame shape: (3, 3)

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
None
